version: "3.8"
name: reservasi
services:
    # Application
    reservasi-app:
        build:
            context: ./docker/services/app
            dockerfile: app.dockerfile
        working_dir: /var/www
        env_file: .env
        volumes:
            - ./:/var/www
        networks:
            - rw-network

    # Web Server
    reservasi-web:
        build:
            context: ./docker/services/web
            dockerfile: web.dockerfile
        working_dir: /var/www
        restart: always
        volumes:
            - ./:/var/www
        ports:
            - "8081:81"
        networks:
            - rw-network

    # Database
    reservasi-database:
        image: mysql:8.0.25
        command:
            --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
        volumes:
            - ./docker/volumes/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: reservasi
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_TCP_PORT: 3308
        ports:
            - "3308:3308"
        networks:
            - rw-network

networks:
    rw-network:
        name: "reservasi-wahana-network"
        external: true
